In [1]:
%pwd

'/Users/Bixing/Google Drive (by783@nyu.edu)/NYU_Courses/Sem2_DL_Proj/DL19_Final_Project'

In [2]:

import torch
import torch.nn as nn
import torchvision

In [3]:
class TEST(torch.nn.Module):
    def __init__(self):
        super(TEST, self).__init__()
        self.encoder=nn.Sequential(nn.Linear(1,1))
        self.decoder=nn.Sequential(nn.Linear(1,1))
        
    def forward(self,x):
        x=self.encoder(x)
        x=self.decoder(x)
        return x

def Get_features(self, _input, _output):
    print('print: input:',_input)
    print('print: output:',_output)
    #return output

def Get_encoder_features(self, input_, output_):
    encoder_output.append(output_)

In [4]:
x=torch.tensor([[1.0]])

In [5]:
model=TEST()

# 如何重设 layer
# https://discuss.pytorch.org/t/load-initial-weights-to-one-layer-of-the-convnet-manually/13336
model.encoder[0].weight.data = torch.tensor([[2.0]])
model.encoder[0].bias.data=torch.tensor([[0.0]])


model.decoder[0].weight.data = torch.tensor([[3.0]])
model.decoder[0].bias.data=torch.tensor([[0.0]])

In [6]:
encoder_output=[]
model.encoder[0].register_forward_hook(Get_encoder_features)

In [7]:
l=model(x)

In [8]:
encoder_output

[tensor([[2.]], grad_fn=<AddmmBackward>)]

In [9]:
l.backward()

In [10]:
model.encoder[0].weight.grad

tensor([[3.]])

In [11]:
model.decoder[0].weight.grad

tensor([[2.]])

In [12]:
model2=TEST()

# 如何重设 layer
# https://discuss.pytorch.org/t/load-initial-weights-to-one-layer-of-the-convnet-manually/13336
model2.encoder[0].weight.data = torch.tensor([[2.0]])
model2.encoder[0].bias.data=torch.tensor([[0.0]])


model2.decoder[0].weight.data = torch.tensor([[3.0]])
model2.decoder[0].bias.data=torch.tensor([[0.0]])

In [13]:
encoder_output=[]
model2.encoder[0].register_forward_hook(Get_encoder_features)

In [14]:
l=model2(x)

In [15]:
l=l+encoder_output[0]

In [16]:
l.backward()

In [17]:
model2.encoder[0].weight.grad

tensor([[4.]])

In [18]:
model2.decoder[0].weight.grad

tensor([[2.]])

# the hook works, can extract the layer vaild layer output ('True' layer output, which remember its position in the computational graph and correctly calculate the grad) 

In [19]:
import sys
sys.exit('stop here')

SystemExit: stop here

/Users/Bixing/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3275: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [ ]:
en_output

In [ ]:
model.encoder[0].weight.data

In [ ]:
l=model(x)

In [ ]:
l.backward()

In [ ]:
model.decoder[0].weight.grad

In [ ]:
de_layer=model.decoder[0]

In [ ]:
en_layer=model.encoder[0]

In [ ]:

de_layer.register_forward_hook(Get_features)

In [ ]:
l=model(x)